# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.box_download_insecure = true

  config.vm.provision "shell", inline: <<-SHELL
    /vagrant/init.sh
  SHELL
end
